#!/bin/bash

port=$1

if [ -z "$port" ] #if port isn't assigned
then
  echo Need to specify port number
  exit 1
fi

FILES=(block.py chain.py config.py mine.py node.py sync.py utils.py)

mkdir kbc$port
for file in "${FILES[@]}"
do
  echo Syncing $file
  ln ./$file kbc$port/$file
done

echo Synced new kbc folder for port $port

exit 1
